### ISSUE TITLE
New contacts in phonebook

### ISSUE THREAD

**Issue by EvertA** [mozillahispano/openwapp#100]
I can not find new contacts through my phonebook.
Also there are no notifications wen people sent a message to me.

**Comment by willyaranda** [comment]
What kind of contacts? The contacts you see in openwapp are shown in the same app as the contacts app, so you are able to see them all.

Notifications in the notifications bar? or in-app?

**Comment by willyaranda** [comment]
What kind of contacts? The contacts you see in openwapp are shown in the same app as the contacts app, so you are able to see them all.

Notifications in the notifications bar? or in-app?

**Comment by EvertA** [comment]
it was the problem that there was no connection with openwhapp. Now it 
is allright.
Tanks.

Op 09-03-15 om 10:51 schreef Guillermo López Leal:
