### ISSUE TITLE
Updating translations

### ISSUE THREAD

**Issue by Airon90** [mozillahispano/openwapp#102]
About a month ago I finished translating and checking the grammar errors in the Italian translations, yesterday I updated OpenWapp but you didn't include the new translations. Could you please fix it? Thank you!

**Comment by Timmaks** [comment]
a little patient please, we are in the middle of moving to transifex and the last update on marketplace (5 feb) was before this. when we are finished with the testing there will be a update and your changes made in transifex 3 weeks ago will be included (the repro is not using the last updates now, if i am sure everything is ok i will update the repro with the latest changes of transifex) 

 we need to make sure that your translation on transifex is used in all the places of the app.

**Comment by willyaranda** [comment]
Thanks for the clear response @Timmaks  :)

**Comment by Airon90** [comment]
Thank you for your answer, Timmaks! ^^ My fear was that you forgot to update the translations!
