### ISSUE TITLE
whatsapp

### ISSUE THREAD

**Issue by ilaeda1992** [mozillahispano/openwapp#112]
Why whatsapp not reinstall why an error come i want it on my home screen

**Comment by mancvso** [comment]
Seems like you've uninstalled it by accident.
Check in the Firefox Marketplace that you have OpenWapp installed on your device. If not, be sure to install it.
If Spanish is your native language, please use it as well.

**Comment by ilaeda1992** [comment]
New version

**Comment by ilaeda1992** [comment]
Why it not proceeding new version in my phone i want download new version now plz help

**Comment by willyaranda** [comment]
There is a new version on the marketplace.
