### ISSUE TITLE
OpenWapp cannot reconnect, no error message

### ISSUE THREAD

**Issue by dee-dw** [mozillahispano/openwapp#114]
After installing OpenWapp on my Mozilla Flame with Firefox OS 1.3 I received some messages for some hours. If I wanted to send a message after this time the message is marked with a red border and the "redo"-icon appears so I think the message was not sent.

I restarted OpenWapp and I see the tag "Offline" in the Inbox. Below the dialogs I just see the loading icon of Firefox OS, so I think OpenWapp trys to connect to the Whatsapp-Server.

Even after half an hour I do not see an error message why OpenWapp cannot reconnect.

In my profil I see that the expiration date is not set even if I have paid the day before yesterday. If I click onto "renew" a new empty page appears with "http://www.whatsapp...." in the url bar. Nothing happens then. I checked that I can visit the whatsapp page in my browser and that works.

So currently I think Whatsapp blocked the OpenWapp login but I do not see why. I have this issue since a week and reinstalled OpenWapp several times since then. OpenWapp will only work for some 12 hours.

**Comment by dee-dw** [comment]
Do you need any more input? Can I give you more data?

**Comment by lumimgardt** [comment]
Have same problem. The app keeps showing offline even when i am connected therefore making it impossible for me to chat. Please i need urgent help

**Comment by Artox** [comment]
Same here. FirefoxOS 2.0, Alcatel tonetouch fire e.
Story: worked fine for several days, with 3g always on.
Then 3g was off for a few hours as I had to save on battery life, and since then, openwapp has been offline no matter if I connect to wifi, 3g, restart phone, restart openwapp ....

Reinstalled, and then still not working. After entering the sms code, I am again at the offline message, and it says loading conversations. Sadly nothing happens then.

**Comment by Artox** [comment]
However here is the curious part: I can't reproduce with a self-compiled build of today.

**Comment by Timmaks** [comment]
please check if you still have this issue with the latest version, and reopen if needed

**Comment by hadyga** [comment]
I have the same problem openwapp worked for 5min after installing it and it became offline
