### ISSUE TITLE
openwapp is not installing on my phone intex cloud fx??

### ISSUE THREAD

**Issue by tanmaycool** [mozillahispano/openwapp#117]
After installation i tried to verify the number but it causes error old version please contact openwapp devs

**Comment by khepriduat** [comment]
Same here.

**Comment by cvrcollege** [comment]
For mee too so plz solve d prblm by leaving help in my email...as soon as possible as it iz urgent

**Comment by Timmaks** [comment]
The work on the fix is discussed in #118
