### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by pdr3947** [mozillahispano/openwapp#120]
I can not sign up again in OpenWapp always appears undefined What do I do now to go back to normal?

**Comment by pmquste** [comment]
I have the same problem since last week. Cant install it.

**Comment by Timmaks** [comment]
can you be more specific, what version do you use, is it a update, what version of fxos do you use etc.

**Comment by Timmaks** [comment]
Closing because no info.

p.s. you get a undefined when something went wrong with the communication to WA. we did not show a right error message, this will be fixed in the next version
