### ISSUE TITLE
1.7.6 doesnt works permanent

### ISSUE THREAD

**Issue by Shadow1g** [mozillahispano/openwapp#121]
The problem with the new client requirements isn solved!

The new 1.7.6 works only for some hours, after this time you lose the connection to the WA-network again and cant reveive or send anything. 

All you can do is to reinstall openwapp, than it works again for some hours, but not permanent...

**Comment by Timmaks** [comment]
I do not see this problem, some times i lose the connection (go offline) but after a app restart it is ok again, did you also try to force close the app and start again so it will try to connect again to WA

**Comment by Timmaks** [comment]
I see now what you mean, after a few hours openwapp goes offline and the only possibility to get online is to close the app and restart it again.

**Comment by LorraineJoubert** [comment]
I seem to have the same problem. Openwapp is supposed to check messages every 5 minutes, or even if set on more. Shows I am offline.Then, when a friends send me a sms, suddenly the whatsapp message comes through.

**Comment by bobcanthelpyou** [comment]
@LorraineJoubert are you connected with a Data connection? Does this occurs every time? Could you use other internet sites or web apps while not receiving messages over OpenWapp?

**Comment by LorraineJoubert** [comment]
Yes, I am connected. I am able to connect to the internet -  use other apps/sites. No I could not determine a pattern to when it occurs/not. Even restarting the phone has no impact on it. Closing and opening the app also does not have an impact.

**Comment by Timmaks** [comment]
It looks like the check messages code doesn't  work as wanted. Can someone have a look at?

**Comment by cmeerw** [comment]
I am seeing similar behaviour with loqui and I think I now understand what's happening: when the phone is sleeping, it only briefly wakes up when receiving data from the socket, but it doesn't always stay awake long enough to be able to fully process and acknowledge an incoming message resulting in the WhatsApp server to close the connection (functions being chained together by "setTimeout" in coseme seems to contribute to this). I am currently testing a fix for this, fingers crossed...

**Comment by Timmaks** [comment]
This is now fixed with the latest coseme, please reopen if you still have this issue
