### ISSUE TITLE
not receiving messages in connectA2

### ISSUE THREAD

**Issue by pavithrashankar** [mozillahispano/openwapp#122]
Iam not receiving any messages in connectA2 please fix it

**Comment by willyaranda** [comment]
This is not Connecta2 repo.

**Comment by pavithrashankar** [comment]
Iam not able to open openwap while trying its showing "old version"

**Comment by Timmaks** [comment]
Have you updated to version 1.7.6 from Marketplace?

**Comment by pavithrashankar** [comment]
How to update

**Comment by Timmaks** [comment]
normally the phone will do that automatically but i believe you can force the update check through the settings menu of your phone.

**Comment by JayVii** [comment]
I think that "feature" doesn't work in FxOS1.3 (at least not for me)
The update-tool will always show "no updates available" and there are no notifications either. So you have to manually look in the marketplace and manually RE-INSTALL the app if you want the new version :S

**Comment by pavithrashankar** [comment]
I have already re installed the app but the the problem is their
