### ISSUE TITLE
update openwapp

### ISSUE THREAD

**Issue by aaronant** [mozillahispano/openwapp#123]
Hi! have quite a simple question: how can I update openwapp to version 1.7.6? When I search openwapp in marketplace it only gives the option "open" not download. Do I have to kill the old version first? And if yes, will all the old conversation be lost after that? Thanks for helping!

**Comment by willyaranda** [comment]
Hi!

The update process is out of our hands. When we push a new version to the marketplac, users should get a notification on their phones that a new version is available (I think it is between 0 and 24h hours of our upload, but I'm not sure).

Removing the old version will mean that your conversations will be deleted, sorry.

**Comment by Airon90** [comment]
Generally you should open Settings > Device Information > Check now

**Comment by leshmat** [comment]
Please mend this openwapp problems now i am regrettin a lot to use firefoxOS
