### ISSUE TITLE
Some group messages are lost

### ISSUE THREAD

**Issue by bobcanthelpyou** [mozillahispano/openwapp#124]
I am a member of a group twice with different numbers and clients
- Firefox OS 2.0 and OpenWapp
- Android Emulator (Android SDK) and WhatsApp

Some messages are not received with OpenWapp, i miss them compared to the same group on the official WhatsApp client.

Could that be just a bad connection problem? Both clients share the same restricted mobile data connection, but are mostly online to different times.

**Comment by adriaon** [comment]
i;ve been missig a few too

**Comment by adriaon** [comment]
how can i help?

**Comment by Timmaks** [comment]
Can someone please verify if this is still a issue?

**Comment by bobcanthelpyou** [comment]
I am sorry, i can't help to test, i don't have a Whatsapp account at the moment

**Comment by B4iken** [comment]
Hello, I just got a WhatsApp account and started using OpenWapp with friends (they are using WhatsApp original) and I didn't receive some messages.

**Comment by ghost** [comment]
As OpenWapp has been discontinued, closing that issue.
