### ISSUE TITLE
Can not create a group with OpenWapp

### ISSUE THREAD

**Issue by oteo** [mozillahispano/openwapp#126]
STR:
1) Create a group
2) Include Group name and participants and press "Done" button

Current Result: Nothing happens, no group is created and this was working in older versions of the application

Note: In case it can helps: Server is receiving a 500 error fault

**Comment by Timmaks** [comment]
please provide more details. witch version of openwapp/fxos/phone/..

**Comment by oteo** [comment]
FxOS: latest master version (today's build 12 Jun 2015)
OpenWapp: 1.7.6 (latest available in the MP)
Device:Flame

**Comment by bobcanthelpyou** [comment]
Same issue with v1.8.1

```
"Error while creating the group: 501" group-profile.js:107
Profile<._createGroup/<() group-profile.js:107
.init/pub.createGroup/_groupCreateRequests[id]() client.js:793
onGroupCreateFail() client.js:306
fireEvent/</<() coseme.js:7456
```

**Comment by Timmaks** [comment]
This is fixed in the current version
