### ISSUE TITLE
Not working anymore in LG Fireweb D300 (Firefox OS 1.1)

### ISSUE THREAD

**Issue by nicholascamp** [mozillahispano/openwapp#144]
I was using it until today, when it "logged off", asking my number again. When I give the number, OpenWapp returns undefined to me.

**Comment by wasi99** [comment]
On Alcatel One Touch Fire, FFOS 1.3 is an error message since 8 hours...
Old Version. Contact OpenWapp devs

Update to new Version (1.8.0 from marketplace): same error

**Comment by cmeerw** [comment]
likely related to mozillahispano/coseme#19

**Comment by Timmaks** [comment]
Did you enter a new code or did you use a old reg code? 

We need a update of coseme to fix this registration error like cmeerw say

**Comment by capsnew** [comment]
I have been redirected here (from https://github.com/mozillahispano/openwapp/issues/145) but I don't understand what I have to do. I have the same error on ZTE Open C.

**Comment by Timmaks** [comment]
@capsnew you have to wait till we have a new version of whatsapp (1.8.1). and for that we have to wait for a update of Coseme. We hope to push this to the marketplace today.

**Comment by capsnew** [comment]
OK thank you

**Comment by Hywan** [comment]
@Timmaks Thanks.

**Comment by Airon90** [comment]
> We hope to push this to the marketplace today.

So, what's the problem, @Timmaks? :)

**Comment by nicholascamp** [comment]
I was receiving undefined, but today OpenWapp updated and when I register it tells me 'old version, contact OpenWapp dev'.

**Comment by Timmaks** [comment]
Coseme has a pull request but the defs didn't aply it yet. We are depending on that.

**Comment by Timmaks** [comment]
I did some changes by hand and pushed that to the marketplace. i hope it get reviewed quick!

**Comment by nicholascamp** [comment]
Nice, Timmaks, thanks.

**Comment by Timmaks** [comment]
New version is aviable

**Comment by Airon90** [comment]
Just a question: why did you push all changes on Marketplace but you didn't change the source code on GitHub?

**Comment by J0WI** [comment]
Thanks for quick the Update!
Would be great to have the changes on GitHub too.

**Comment by Hywan** [comment]
:+1:

**Comment by Timmaks** [comment]
I modified the local coseme file in my build config, as soon coseme has a new version the build config of openwapp on github will be updated so itwill use that new version

**Comment by capsnew** [comment]
Everything is back to normal for me, thank you everyone (y)

**Comment by Timmaks** [comment]
@J0WI the fix is now in the 1.8.x branch with label 1.8.1
