### ISSUE TITLE
The last update hasn't resolved the problem in my smartphone

### ISSUE THREAD

**Issue by jssCAT** [mozillahispano/openwapp#149]
Hello everybody,

I want to tell you that I'm having problems with Openwapp. I have uninstalled the previous Openwapp version and I have installed the new update, but it doesn't work correctly. The sesion is "offline" permanently, and it doesn't load the chats. My smartphone is an Alcatel One Touch Fire E, and the version of Firefox OS is 2.0.

Thank you!

**Comment by cmeerw** [comment]
I believe WhatsApp was down today for some time, are you still having issues connecting?

**Comment by jssCAT** [comment]
Yes! I have tried to connect Openwapp another time, and now it works very well! Even it works better than the previous version. Thanks for the information! :)
