### ISSUE TITLE
Can't sign up (Old version, please contact OpenWapp Devs)

### ISSUE THREAD

**Issue by Nairolf21** [mozillahispano/openwapp#151]
Hi, 

I was a happy user of OpenWapp. But, I've moved in the US, and changed my SIM card. Now, I can't sign up with my new phone number... 

I'm trying to register, I type my phone number. And during the phone validation process, it's stopped, and I have a pop up which says "Old version, please contact OpenWapp devs". 

I don't know how to find the number of version I used. I'm on the ZTE Open C, and with Firefox OS 1.3. What I have to do ? 

Thank you

**Comment by Timmaks** [comment]
You have to check for the new version in marketplace. Fxos->settings->device information->check for updates->check now.

@willyaranda can we use the {{version}}label from the openwapp settings also in the old version warning? Users have no way now to see witch version the have if they hit this warning.

**Comment by willyaranda** [comment]
@Timmaks yes, sure!

or even the currentCommit https://github.com/mozillahispano/openwapp/search?utf8=%E2%9C%93&q=currentCommit

**Comment by Timmaks** [comment]
This error screen has now a versionnumber, commit 60fb22fa3634ef9aa7f40d872f4d01c8d13c7c03

**Comment by kotimohan** [comment]
Hi,

I was a happy user of OpenWapp. Suddenly it stopped, tried almost every thing but won't open then I uninstalled it.

I'm trying to register, I type my phone number. And during the phone validation process, it's stopped, and I have a pop up which says "Old version, please contact OpenWapp devs".

I don't know how to find the number of version I used. I'm on the Alcatel Fire C Onetouch FireC 4020D Mobile Phone, and with Firefox OS 1.3. What I have to do ?

Thank you..

Regards,
Koti.

**Comment by ngoymwembo** [comment]
Hi really forgot my code to sing in

**Comment by kotimohan** [comment]
Hi Timmaks, Thank you for response but, you given some instruction those are not performed in my alcatel one touch mobile . can you respond quickly plz...

Regards,
Mohan.
