### ISSUE TITLE
Profile pic

### ISSUE THREAD

**Issue by LorraineJoubert** [mozillahispano/openwapp#153]
When configuring, I loaded a profile pic. However, only after uninstall and installing another client(ConnecA2) could friends see my pic - I did not load it again.

**Comment by bobcanthelpyou** [comment]
Your friends use the official WhatsApp Messenger? Did you setup the picture while OpenWapp was offline? Maybe it updated the profile picture later when you receive a SMS as you said here: https://github.com/mozillahispano/openwapp/issues/121#issuecomment-126372138

**Comment by LorraineJoubert** [comment]
Yes, my friends use the official WhatsApp. I set-up the picture when installing OpenWapp. No - the whole 3 weeks I was using OpenWapp they could not see my picture.

**Comment by Timmaks** [comment]
This is strange, if your picture is appearing when you use a other client without setting is again it means that your picture was in your profile on the whatapp servers. The different clients does not use the same local profile.

We need confirmation on this from someone else

**Comment by Loirooriol** [comment]
I have this problem too. I loaded a profile pic using OpenWapp but other people (with official WhatsApp) can't see it. If I start a conversation with myself, I don't see it neither. But when I go to configuration in OpenWapp, the image is there.

**Comment by Loirooriol** [comment]
Updating to version 1.9.0 fixed the problem for me.
