### ISSUE TITLE
Can't install: Blocked

### ISSUE THREAD

**Issue by LorraineJoubert** [mozillahispano/openwapp#154]
When installing OpenWapp / waiting for validating number, I receive a status fail, reason blocked message

**Comment by bobcanthelpyou** [comment]
Which OpenWapp and Firefox OS version do you use? What is the complete error message?

**Comment by LorraineJoubert** [comment]
I am using the Firefox OS 2.0.0.0 -prerelease. 
I am trying to install the OpenWapp version that is on the Firefox marketplace - it does not show which version it is.
"OpenWapp
Oops, error. Message=(
"status": "fail",
"reason": "blocked"
)

**Comment by Timmaks** [comment]
As i read in the various  issues you filed (thanks!) You have also used connecta2, if you use at the same time or request often a activation  code you get blocked by WhatsApp.  This means you have to contact them to get activated, but remember openwapp and connecta2 are not a official client and you are violated their user agreement by using it

**Comment by bobcanthelpyou** [comment]
I think i got blocked before and i had to wait for some days or weeks to get unblocked again. I didn't contact WhatsApp.

**Comment by Timmaks** [comment]
Are you saying that you can register when you use connecta2 but not when you use openwapp?

**Comment by LorraineJoubert** [comment]
No, because of the issues I had with OpenWapp, I moved to Connecta2. OpenWapp uninstalled itself then. Connect A2 suddenly could not "connecting to the network " the whole day. I uninstalled and re-installed but received a message that it is   "unable to send sms". So then I tried OpenWapp.

**Comment by LorraineJoubert** [comment]
OK, but how on earth do I know what whatsapp user agreement is, as they do not have an app for Firefox.
