### ISSUE TITLE
Logged out & can't log in back (status: fail, reason: blocked)

### ISSUE THREAD

**Issue by nicholascamp** [mozillahispano/openwapp#156]
{
"status": "fail",
"reason": "blocked"
}

I was using OpenWapp normally, when I was unable to send messages, so I closed it and opened again. A screen asking me to register again appeared, and I was unable to do it because the above error message. Could you tell me what's going on? Thanks in advance.

**Comment by bobcanthelpyou** [comment]
Are you using the latest version of OpenWapp from the Marketplace, could you check for updates? And did you try to use a different Wapp client? Or did you do something every different? What Firefox OS version and phone do you use?

**Comment by nicholascamp** [comment]
LG D300 Fireweb, Firefox OS v1.1. Yeah, I think it's the latest OpenWapp. I am with internet and no updates are showing. When I could not connect to OpenWapp, I tried Loqui IM, without success.

**Comment by bobcanthelpyou** [comment]
It could be the problem that you tried to use Loqui IM, switching between devices (or clients which act as different devices) in a short time could block your number for some time.

When apps have problems with their functionality, sometimes it helped to restart my Firefox OS device.

I will try to get blocked, too. Let you know when i found a way to get unblocked.

**Comment by nicholascamp** [comment]
I only used it when I was unable to reconnect (and got the error). I restarted the phone and still can't connect

**Comment by bobcanthelpyou** [comment]
How are you connected? Wifi or mobile data connection? 

I tried to reproduce a blocked error message but i only receive the following when requesting to much confirm codes in a short time

![index](https://cloud.githubusercontent.com/assets/4523264/9023445/83798388-389b-11e5-8564-bb612719fcac.png)

**Comment by nicholascamp** [comment]
Wifi.

**Comment by nicholascamp** [comment]
Is there a way to force the verification of apps updates?

**Comment by nicholascamp** [comment]
I went into configurations > informations > software updates and 3 apps got updates, but none of these was WhatsApp related (OpenWapp, Loqui IM).

**Comment by willyaranda** [comment]
Blocked is because WhatsApp blocked your number. We can't do anything right now about that. If you contact WA, you will be told that OpenWapp is not supported.

You can wait for unblock a few days

**Comment by nicholascamp** [comment]
Why was I blocked?

**Comment by willyaranda** [comment]
OpenWapp is NOT an official app. You might be blocked for using this app, because you are not following their terms of service (https://www.whatsapp.com/legal)

**Comment by nicholascamp** [comment]
Understood. Thanks for the information. Hope that it get back soon. Do you have an idea how long will it delay?

**Comment by nicholascamp** [comment]
Still blocked.

**Comment by Timmaks** [comment]
If you still have problems please reopen
