### ISSUE TITLE
Can't receive message from Android (FFOS 2.0)

### ISSUE THREAD

**Issue by Trynight** [mozillahispano/openwapp#157]
![11857546_656953087773780_348093581_n](https://cloud.githubusercontent.com/assets/4656862/9150291/bbc38a0a-3dd1-11e5-9f86-a60a485eba31.jpg)
![2015-08-08-13-29-31](https://cloud.githubusercontent.com/assets/4656862/9150292/bbcc6d46-3dd1-11e5-807d-11c2d4452a27.png)

The same problem on LoquiIM.... who else have this problem?

Firefox2.0-prerelease (i will update to 2.5 today)

**Comment by Trynight** [comment]
tested with 2.5 ... nothing changed

**Comment by Trynight** [comment]
i can't receive messag from iOS Whatsapp too

**Comment by Charlywhat** [comment]
Same thing here, I can send messages, but cannot receive them.
Alcatel OT Fire E (Firefox OS v2.0)

**Comment by Trynight** [comment]
@Timmaks @willyaranda

**Comment by Timmaks** [comment]
this should be fixed in version 1.9.0
