### ISSUE TITLE
"Loading conversations..." message never disappears

### ISSUE THREAD

**Issue by Loirooriol** [mozillahispano/openwapp#162]
The "Loading conversations..." doesn't disappear even if all conversations have been loaded.

I debugged and the problem is

1. In `scripts/collections/history.js`, `_syncGroups` uses `global.client.getGroups` to get the list of groups.
3. In my case the list of groups is an array with one one item: `{ gid: null, subject: "" }`. (In fact I have two groups, but it seems internally they are treated as conversations, is this normal?)
4. `findOrCreate` is called for each group in the array
5. If `findOrCreate` receives a `null` id, the callback is not called

I fixed it by adding this code at the beginning of `findOrCreate`:

```javascript
if(id === null) {
  callback('Error: "id" is null', {
    isNew: false,
    conversation: null
  });
  return;
}
```

Not sure if the first parameter `err` is supposed to be a string or an `Error` object or whatever. But it's ignored, so doesn't seem to matter.

However, that code only addresses the symptom, but the real cause seems that `parseGetGroups` in `components/coseme/dist/coseme.js` receives a list with errors:

```javascript
node = {
  _data: null,
  _tag: "iq",
  attributes: {
    from: "g.us",
    id: {...},
    type: "error"
  },
  children: [{
    _data: null,
    _tag: "error",
    attributes: {
      code: "501",
      text: "feature-not-implemented"
    },
    children: []
  }]
}
```

**Comment by Loirooriol** [comment]
Fixing coseme.js with [#24](https://github.com/mozillahispano/coseme/pull/24) and [#25](https://github.com/mozillahispano/coseme/pull/25) should solve this problem.

**Comment by telefrancisco** [comment]
This is happening in 1.9.0: https://twitter.com/djoerd/status/659066284936667136

**Comment by Timmaks** [comment]
thanks @telefrancisco we have noticed this problem also and working on finding the problem

**Comment by Loirooriol** [comment]
@telefrancisco That is a different bug, I have filed #166

Once that is fixed, the change in coseme solves this one in 1.9.0.

**Comment by telefrancisco** [comment]
@Loirooriol Thanks for all. Let's hope to see this solution soon in the Marketplace.
