### ISSUE TITLE
Old version, please contact OpenWapp devs

### ISSUE THREAD

**Issue by SwarnaKishore** [mozillahispano/openwapp#165]
I could see that the errors is set in properties for 'registerErrorOldVersion' but I just installed OpenWapp from Firefox Marketplace. Any thoughts?

I am using Firefox Open device.
If there is anymore information that could help debug, please let me know

Thanks!

**Comment by philip13** [comment]
I have the same problem, went I want to sign-up say: "Old version, please contact OpeWapp devs"

**Comment by xev2000** [comment]
Hello;
since the update on 25th October, I need to sign in again and when  I try it says "Old version, please update or contact OpenWapp devs"
with the 10/28 update it's the same, restarting the smartphone couldn't help either
OS is FFOS 1.3 on ZTE
any suggestions how I can update manually?
Thanks in advance

**Comment by Kiude** [comment]
Hi everyone! I have the same problem described above. I understand that the upgrade has been released yesterday. My question is about the upgrading process: is there a direct upgrade option on the marketplace, or should i manually uninstall and re-download the app?
More important: will my data be safe if I do so?
 Thanks in advance! :)

**Comment by Timmaks** [comment]
Don't uninstall the old version! This will delete your data. Restart your phone and the marketplace will promt for a update.

**Comment by Kiude** [comment]
Hi! Thanks @Timmaks, I was very suspicious about uninstalling. Now I know! :)
OK, I tried rebooting the phone, opening several time the marketplace, openwapp itself but at no moment a message of re-upgrading appeared.. I am so close to having the problem solved, so frustrating! Haha

**Comment by cmeerw** [comment]
@Kiude what phone do you have? Is it by any chance a ZTE Open C with the original 1.3 firmware?

**Comment by Timmaks** [comment]
And if you go to settings, Device information,  check for updates?

**Comment by Kiude** [comment]
Hi @cmeerw!  Sorry I should have said it at the beginning: I have indeed an Open C with the 1.3.0.0 
when I ask for updating the OS with the app-button on the desktop,  it says I am at the most recent version.

**Comment by Omega246** [comment]
@Kiude I dont know if you want to upgrade your phone, but if you consider it, you should look at this page:
http://builds.firefoxos.mozfr.org/doc/en/devices/zte-open-c?redirect=1

Maybe some devs here know a better way. But for me it worked quite nicely. (Until i lost my phone. :(  )

**Comment by cmeerw** [comment]
You could give this one a try:

  http://download.cmeerw.net/fxos/CheckUpdate-1.2.zip

You'll need to unzip and install it through WebIDE to your phone, also
see https://bugzilla.mozilla.org/show_bug.cgi?id=1030626

**Comment by Kiude** [comment]
Interesting link @cmeerw ! I believe your CheckUpdate app is the solution! I had to wait for access to a computer, I am now busy with making my device recognized on WebIDE (newbie here..). I'll get back to you once I test the app.
