### ISSUE TITLE
No conversations in 1.9.0

### ISSUE THREAD

**Issue by Loirooriol** [mozillahispano/openwapp#166]
Openwapp 1.9.0 fails to load the conversations. See https://twitter.com/djoerd/status/659066284936667136

The cause is at line 56 of contact.js:

```javascript
this.get('isGroup') && (this.get('creator').split('@')[0]));
```

The problem is that there is no `creator` attribute, so `this.get('creator')` returns undefined. And attempting to call a method of undefined throws.

The culprit is https://github.com/mozillahispano/openwapp/commit/e4df71af47e1da874a64492cea645997ca07074f. Please backout it.

**Comment by willyaranda** [comment]
Backed out in 93cbd769167b53b2539108f2fd93f1875aadece7

Thanks!
