### ISSUE TITLE
Cant connect to the Network, Registration fails

### ISSUE THREAD

**Issue by Omega246** [mozillahispano/openwapp#169]
Hello folks, 
First: Sorry for my bad english. ;)

Data: Firefox OS 2.0 
Alcatel onetouch Fire E, 
latest Openwapp Version 1.9.1-0-g7c6d673

It happend today. My moblie phone couldnt connect to the Network. Ist was offline. I restarted the App and the registration screen appeared.
I tried to registrate my phone many times, but every time it cant conect to the network (the Inbox ist loading vor 4 secs) and the registration screen apperes again.
I restarted my phone, i reinstalled the app, but nothning works.

One time i got the Code. But using it put me first in the Profile Menue then, after typing my name, the inbox-screen loads for some seconds and i am back to the reg-screen.

Now i am stuck there. Its now: Typing Number>Profile menue>Inbox>Registration>Typing Number>Profile menue...and so on..

If you need some more information to solve this problem, plz let me know.

Thank you for all your Effort.

**Comment by jambolo1970** [comment]
confirm ,same problem from italy

**Comment by adriaon** [comment]
confirmed (Flame).

**Comment by Timmaks** [comment]
Can someone try to replicate this issue using webide and post the log here?

**Comment by jssCAT** [comment]
Yes, I also have the same problem (Alcatel OT Fire E).

**Comment by Omega246** [comment]
@Timmaks 

I tried it now for 2 hours. My Windows 7 Pc+ Webide couldnt find The Phone. 

I read this: https://developer.mozilla.org/en-US/docs/Tools/WebIDE/Troubleshooting
and followed the instructions.

and after i installed some drivers in a wierd way (http://pichoster.net/image/UZy), now Webide find the Phone. But if i try to open the OpenWapp App or any other app i get:

Error1: http://pichoster.net/UZd
Timeout on Operation
or
Error2: http://pichoster.net/image/UZw
"Cant connect to the App"

Maybe someone else have Linux or some easier shot than me on this topic. Just use Shift+F8 in Firefox and try it.

**Comment by bidaian** [comment]
I can replicate it, but I see no debugging info from OpenWapp when using WebIde (after this[1]). I also tried 'adb logcat' but there's no openwapp information to be seen, just generic wpa, b2g stuff.

[1] https://developer.mozilla.org/es/docs/Tools/WebIDE/Troubleshooting#Activando_el_log

**Comment by cmeerw** [comment]
You'll likely want to have a look at https://github.com/loqui/im/commit/648926c6b19d66fddc7d2fb8b7bb23fc3e94e7cd

**Comment by inytar** [comment]
I can reproduce using the webide. Using a Alcatel OT Fire E (6015X):
The log:
````
FUD Tue Oct 27 2015 15:20:16 GMT+0100 (UTC) fxosrate.js:82
[background service] Started background-service.js:26
[background service] Next awake signal with id 105792 by Fri Nov 06 2015 23:36:33 GMT+0100 (UTC) background-service.js:88
OpenWapp: getting the seed. client.js:38
GET 
https://v.whatsapp.net/v2/register [HTTP/1.1 200 OK 884ms]
GET 
https://v.whatsapp.net/v2/register [HTTP/1.1 200 OK 379ms]
OpenWapp: getting the seed. client.js:38
[background service] Awake signal received. background-service.js:46
[background service] Service down, reconnecting! background-service.js:50
[background service] Next awake signal with id 105793 by Fri Nov 06 2015 23:41:33 GMT+0100 (UTC) background-service.js:88
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
GET 
https://v.whatsapp.net/v2/register [HTTP/1.1 200 OK 540ms]
OpenWapp: getting the seed. client.js:38
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
````

The GETs are when trying to registrate. They return:
````
{"status":"fail","reason":"stale"} 
````
@Timmaks Anything else you need?

**Comment by Loirooriol** [comment]
See  Loqui IM's [\[WhatsApp\] suddenly stopped connecting, and SMS verification fails #872](https://github.com/loqui/im/issues/872).

**Comment by jambolo1970** [comment]
@Loirooriol  not function even Loqui IM, both they require properly texting but do not accept the code and return to the reintegration of the Code xxx-xxx

the log in console webIDE of OpenWapp:
OpenWapp: getting the seed. client.js:38
 *** currentView has NOT been cleared router.js:214
OpenWapp: getting the seed. client.js:38
[auth] Logging in... auth.js:69
Already authenticating. Aborting. client.js:562
 *** currentView has NOT been cleared router.js:214
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
 *** currentView has been cleared router.js:212
DAYS 1 fxosrate.js:142
App has not been yet used enough fxosrate.js:122
 *** currentView has been cleared router.js:212
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[auth] Error in login. Retrying every 5 seconds... auth.js:122
[auth] Logging in... auth.js:69
[background service] Awake signal received. background-service.js:46
[background service] Service down, reconnecting! background-service.js:50
[auth] Logging in... auth.js:69
Already authenticating. Aborting. client.js:562
[background service] Awake signal received. background-service.js:46
[background service] Service down, reconnecting! background-service.js:50
[auth] Logging in... auth.js:69
Already authenticating. Aborting. client.js:562
[background service] Awake signal received. background-service.js:46
[background service] Service down, reconnecting! background-service.js:50
[auth] Logging in... auth.js:69
Already authenticating. Aborting. client.js:562
[background service] Next awake signal with id 1628019 by Sat Nov 07 2015 08:48:57 GMT+0100 (CET) background-service.js:88
[background service] Next awake signal with id 1628020 by Sat Nov 07 2015 08:48:57 GMT+0100 (CET) background-service.js:88
[background service] Next awake signal with id 1628021 by Sat Nov 07 2015 08:48:57 GMT+0100 (CET)

**Comment by Loirooriol** [comment]
Fixed by [pull #31](https://github.com/mozillahispano/coseme/pull/31/commits).

**Comment by Timmaks** [comment]
This sould be be fixed with the new version 1.9.2 (coming soon to the marketplace)

**Comment by Timmaks** [comment]
New version is now aviable in Marketplace

**Comment by adriaon** [comment]
👍
