### ISSUE TITLE
Doesn'T work...

### ISSUE THREAD

**Issue by Gabgo** [mozillahispano/openwapp#170]
Hi! I've installed this app but when I open it shows a white screer and do anything else. What can I do? Firefox os alcatel. Si'm sorry about my poor english. Thanka a lot!

**Comment by jssCAT** [comment]
Hi,

For the moment, it seems that it's not possible to connect to the network. If you want, you can take a look to the different messages that will be published here, in the "Issues" section, during these days. Probably, will appear in brief a notification announcing that the problem have been solved. I think that developers are working on it.

Greetings!

**Comment by Timmaks** [comment]
New version is now aviable in Marketplace

**Comment by Gabgo** [comment]
Thanks a lot!!
best regards!!

2015-11-08 8:13 GMT-03:00 T.M. van den Broek <notifications@github.com>:
