### ISSUE TITLE
can only receive messages posted into groups

### ISSUE THREAD

**Issue by MartinSauer** [mozillahispano/openwapp#171]
I installed the new version1.9.2. But now I can only receive messages posted into groups. Messages from single users don´t reach me. Tested with different users using originla WA on android.
Sending is all fine.

(FFOS 2.2. on Open C)

Greetings, Martin

**Comment by cmeerw** [comment]
If you happen to have an Android phone with WhatsApp handy, could you send a test message to +447961596923 please?

**Comment by Timmaks** [comment]
Just send

**Comment by Timmaks** [comment]
Have blue ticks so whatsapp tells me you read it...

**Comment by cmeerw** [comment]
Thanks a lot @Timmaks - it looks like I might have a fix for this issue. Essentially, we need to reply with an error when receiving an encrypted message and then get the plaintext message delivered.

**Comment by Timmaks** [comment]
Great news, looking forward to the PR :)

**Comment by cmeerw** [comment]
Please see loqui/im#882 for the coseme changes that have been implemented in Loqui.

**Comment by jesobreira** [comment]
I can confirm the same problem on Firefox OS 1.1 (LG Fireweb) with latest OpenWapp version as of today (just downloaded it).

**Comment by Timmaks** [comment]
this should be fixed in the new version 1.9.4, please reopen if you still see this problem
