### ISSUE TITLE
Unable to receive registration code 

### ISSUE THREAD

**Issue by jesobreira** [mozillahispano/openwapp#172]
I'm unable to receive the registration code by SMS or phone call.

I'm from Brazil, my carrier is Oi and I didn't have problems using Disa on Android.

No error is show. It just tells me to wait for the code and enter it on the fields, but its never received.

I could never use OpenWapp. I'm on a LG Fireweb running FxOS 1.1.

Registration is actually broken or that's just with my number?

**Comment by Timmaks** [comment]
As far as i can tell is the call for a registration ok  at this moment, are you sure you add your number ok?

**Comment by jesobreira** [comment]
Yes. It worked with Loqui IM (I could receive the code through call - not SMS - but with Loqui the messages weren't being showed, so I still can't use Whatsapp on my phone). With OpenWapp, however, I could not receive the code in any way.

If it helps, plz tell me your email address so I send my phone number.

**Comment by cmeerw** [comment]
@jesobreira Was this the Loqui version from the marketplace you tried? Would you be able to test the current development version of Loqui (to see if you can receive messages with that version)?

**Comment by jesobreira** [comment]
Hi, thanks for the attention!

Today I could receive the code by SMS. Nothing was done by me, tho. I guess it was some update (?).

I could even contribute with a better pt-br l10n ( #177 ), as it's too confusing. However, I faced more problems. To don't mix up the things, I've filled a new issue: #178
