### ISSUE TITLE
localisations/translation does not contain all available locales

### ISSUE THREAD

**Issue by naitsirch** [mozillahispano/openwapp#175]
`app/scripts/localisations/translation.js` starts with the comment

> //This file need to be removed, it is still in the require list

it contains only one locale, which is "en-US".
In `app/scripts/utils/language.js :: getLanguage` this collection is used to check if the system's locale is valid. But the expression is always `false` except for `en-US`. Is this behaviour wanted?

**Comment by Timmaks** [comment]
Yes. Localization was done by this scipt in the past and is now done witl the l10n.js script from gaia. But the build is failing if i totally remove this script and my knowledge of it is not good enough to remove (find) all the calls to this script. If you can remove it you are welcome.

**Comment by naitsirch** [comment]
Okay, but we need a way to check if the user's locale is one of the available localizations. I have not dived into the l10n.js script so much, yet, but maybe [this function](https://github.com/mozilla-b2g/gaia/blob/B2G_2_2_20151029_MERGEDAY/shared/js/l10n.js#L1587) will be helpful.

**Comment by Timmaks** [comment]
the l10n.js does check it, when the locale of the phone is not available in openwapp it will default to en-US. we only need to remove the last parts of the old l10n system, the folder localization, i removed almost everything except this file because it is called from somewhere else. As i understand now from language.js.  So probably this file need to removed also.

**Comment by naitsirch** [comment]
Yes, but my goal was to replace the hardcoded locale 'es-ES' in `app/scripts/views/login.js :: register` function ;-) to achieve that, I need the user's locale.

But I think it is also possible to get the locale from `navigator.language`.
