### ISSUE TITLE
stopped working here->Sign-up>failed/blocked

### ISSUE THREAD

**Issue by adriaon** [mozillahispano/openwapp#181]
When I open the app I get the Sign-up screen. When I try to sign-up i get

Oops, error. Message={"status": "fail", "reason": "blocked" }

Cheers.

**Comment by Timmaks** [comment]
Have you used a other client the last days? This message mean you are blocked by whatsapp and that is something we can not change. Wait a few days is sometimes the solution

**Comment by adriaon** [comment]
Not used another client. Will wait a bit.

**Comment by adriaon** [comment]
Still blocked :-(. Should I try offcial client?

**Comment by Timmaks** [comment]
you can try

**Comment by adriaon** [comment]
I tried with the offical app on an old phone. Still banned, so I contacted WhatsApp Support. They replied with

[..]
Your WhatsApp account was banned because you violated our Terms of Service and were using an unauthorized application and/or unsupported device.
[..]
Should we determine that your actions continue to violate our Terms of Service, your account will be permanently banned and there will be no possibility of an appeal.
[..]

Not sure how how I should proceed...? Anyone else been at this point?

**Comment by Timmaks** [comment]
i am really sorry that  you have this problem. 

I and many other don't have a problem with using a unauthorized app and Whatsapp and i don't understand why you encounter this. I don't give you any advice on this, you must decide if it is worth the risk to get banned
