### ISSUE TITLE
Marketplace version does not work on 2.0

### ISSUE THREAD

**Issue by EdoPut** [mozillahispano/openwapp#195]
The phone is the Alcatel Onetouch [Fire E][fire_e] updated to the latest version available by producer (2.0) and the app is the 1.9.4 from the marketplace.

The app installs and is recognised by the OS but shows a white screen when opened and I can't register.

Phone info:
Os version 2.0.0.0
firmware revision 01010b
platform version 32.0
language en-US

![the app loads](https://cloud.githubusercontent.com/assets/4076473/12371834/26cc8c0a-bc41-11e5-87c2-c804de17b0c5.jpeg)
![the app show a white screen](https://cloud.githubusercontent.com/assets/4076473/12371835/26d04624-bc41-11e5-93d0-3cab09d64809.jpeg)

[fire_e]: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Phone_guide/Alcatel_One_Touch_Fire_E

**Comment by Timmaks** [comment]
Can you use webide in firefox to fetch to log  and paste it to here?

**Comment by Timmaks** [comment]
it looks like your phone is set to en-US language is that right?

**Comment by EdoPut** [comment]
the language is en-US, the log is WIP

**Comment by Timmaks** [comment]
ok thanks, see https://developer.mozilla.org/en-US/docs/Tools/WebIDE/Running_and_debugging_apps#Unrestricted_app_debugging_%28including_certified_apps_main_process_etc.%29 for setting webide to see all the installed apps

**Comment by Timmaks** [comment]
Is this still a issue with the latest update?

**Comment by Timmaks** [comment]
no comment in last 25 days so closing. If this is still a issue please reopen
