### ISSUE TITLE
Wapp update/App cant connect to Service

### ISSUE THREAD

**Issue by Birnd** [mozillahispano/openwapp#196]
If u start the Apps it loads up the Contacts and last Messages with "offline" in the corner, when connected to the Internet it swaps to "Enter Sms Code", which doesnt work.

**Comment by jambolo1970** [comment]
me too, require new code, and the request says outdated version

**Comment by Nordfriese57** [comment]
It's the same in the german version. It's the same in Loqui IM.

**Comment by willyaranda** [comment]
Will work on this during the weekend.

**Comment by cmeerw** [comment]
@willyaranda any ideas what to do?

I believe the options are: update the version sent in the resource string to something like 2.13.30, but this will switch on encryption for group messages which we can't handle. Other option is to use an "invalid" or empty resource string when connecting, but this could increase the likelihood of getting blocked completely...

**Comment by TheElber7** [comment]
Boa tarde, tenho um aparelho LG D300 Fireweb e ontem quando entrei no OpenWapp pediu um novo codigo, desinstalei e instalei denovo, digitei o código recebido e apareceu uma mensagem: "Versão Antiga. Por Favor Contate equipe de desenvolvimento." Fui no Market Place não achei nenhuma atualização nova. Espero que resolvam meu problema. Grato pela Atenção.

**Comment by rodrigoasmacedo** [comment]
Buenas tardes, tengo un dispositivo de LG D300 Fireweb y ayer cuando entré en la OpenWapp solicitó una nueva contraseña, desinstalado e instalado de nuevo, tecleó el código recibido y apareció un mensaje: "vieja versión comuníquese con el equipo de desarrollo .." Yo estaba en el Market Place encontró ninguna nueva actualización. Espero que resolver mi problema. Agradecido por la atención.

**Comment by Boersenfeger** [comment]
Todos los usuarios se ven afectados.
Tenemos que esperar hasta que los desarrolladores han encontrado una solución.
Otras aplicaciones para WhatsApp tampoco funcionan.

**Comment by willyaranda** [comment]
@cmeerw have you tried something to fix this issue?

**Comment by cmeerw** [comment]
@willyaranda the proper fix would be to implement encryption support which is not realistic any time soon. Just updating the version in the tokenData will break group conversations as these will then be encrypted (and the "plaintext-only" workaround doesn't work for group conversations). So the only remaining option I am seeing so far is to use an empty string for tokenData.r - this seems to work for me so far, but I am worried that this could lead to the account being blocked by WhatsApp as it's then very obvious that it's not an official WhatsApp client.

**Comment by willyaranda** [comment]
I just pushed a new CoSeMe version, 1.1.4 that fixes registration problem. I just tested and it works!

https://github.com/mozillahispano/coseme/commit/0ecb487c67443f3786d876bd1a39214ae51f0bef

I have sent a new version to the marketplace and is awaiting review!

**Comment by cmeerw** [comment]
That "fix" will break group conversations (as most group messages will be received encrypted and therefore lost).

**Comment by willyaranda** [comment]
I have tested with a few groups (with latest android on the marketplace) and they are showing correctly. Did I miss something @cmeerw?

**Comment by cmeerw** [comment]
Loqui used to use a version >2.13.9 for a brief period at the end of November - if you look at the properties you get from the WhatsApp server you will now see 'prop name="e2e_groups" value="1"' and some group messages might arrived encrypted (for me it was around 50% - I don't know why it was only about half)...
BTW, it was very unpredictable - the same user writing in 2 different groups: messages in one group were only received encrypted, messages in the other group were received in plain text.

**Comment by cmeerw** [comment]
Ahh ok, 2.13.21 actually does still work (I thought anything higher than 2.13.9 would already cause these issues), anything higher than that will not work for group messages.
