### ISSUE TITLE
Code required - version too old

### ISSUE THREAD

**Issue by MartinSauer** [mozillahispano/openwapp#197]
On 22nd Jnauary OpenWAPP suddenly announced me to type in my registration code which I didn´t request. After trying to make a new request for the code, openwapp told me that my version might be too old. But I have the newest available version 1.9.4.
(Latest aurora on Open C ebay)
Kind regards, Martin

**Comment by Timmaks** [comment]
There is a new version 1.9.5 aviable in the marketplace who fixes this problem
