### ISSUE TITLE
Código de acesso

### ISSUE THREAD

**Issue by TheElber7** [mozillahispano/openwapp#199]
Tenho um lg fireweb d300 estava usando o openwapp normalmente até q pediu um novo codigo, quando confirmo o numero rapidamente abre e fecha uma janela de erro, da qual eu não consegui ler direito mas parecia estar escrito "fail" "status" "blocked". Tentem resolver por favor, o OpenWapp é muito util.

**Comment by naitsirch** [comment]
If you'd write in English the chance to get an answer would be greater ;-)

**Comment by Timmaks** [comment]
i can only read "fail" "status" "blocked". this is somethinmg we can not fix. 

you are blocked by whattsapp for some reason (using a other client (not the official one) can be the  reason) i am sorry.

try again in some days, sometimes it get fixed
