### ISSUE TITLE
Registration not working

### ISSUE THREAD

**Issue by jopigithub** [mozillahispano/openwapp#201]
I was using the app normally and it suddenly jumped to the registration screen. I was not able to complete registration using the sms code (PIN invalid) nor registering with other telephone number (Error: {"status": "fail", "reason": "blocked"}).

**Comment by Timmaks** [comment]
Witch version do you use, is it the latest version? 
Reason "blocked"is something we can not change, whatsapp did block your account but i want to know what is the reason that they blocked you (and not all the openwapp users)

**Comment by jopigithub** [comment]
Yes, I have the latest version (1.9.5) . I thought the problem was like the one recently fixed with last update (January 23), didn't know it was not reaching other users.

**Comment by brendafogam6** [comment]
No I have the old version and I can't register into the new want help pls

**Comment by brendafogam6** [comment]
I try to redgister with my number, but there keep on telling me to contact openwapp devs which I did. Why is this whatsapp so difficult

**Comment by Timmaks** [comment]
It is whatsapp itself who is difficult, they change there version code once i  a while and block all the cients with a dirrent code. We can only react by follow that change, but that takes time because we need to check if everything is still compatible. 

You are all welcome to help to fix this as soon as possible.

**Comment by Timmaks** [comment]
there are 2 issue here reported, blocked and old version.

the old version issue where a i talked about in my last comment and see issue #204 

the blocked issue is something we can not fix
