### ISSUE TITLE
Vermutlich alte Version aktualisieren Sie die App oder kontaktieren Sie Openwapp Entwickler

### ISSUE THREAD

**Issue by aticat** [mozillahispano/openwapp#205]
Error for registration, please fix an update. CG

**Comment by Timmaks** [comment]
dupe of #204

**Comment by aticat** [comment]
Hi,
 
what are the plans to solve this from?
 
Chirine
 
-----Ursprüngliche Nachricht-----
 Von: "T.M. van den Broek" [notifications@github.com]
 Gesendet: Mi. 23.03.2016 10:41
 An: "mozillahispano/openwapp" [openwapp@noreply.github.com]
 Kopie: "aticat" [chirinegramke@freenet.de]
 Betreff: Re: [openwapp] Vermutlich alte Version aktualisieren Sie die App oder kontaktieren Sie Openwapp Entwickler (#205)

Closed #205.
—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
-----Ursprüngliche Nachricht Ende-----
 

---
Alle Postfächer an einem Ort. Jetzt wechseln und E-Mail-Adresse mitnehmen! Rundum glücklich mit freenetMail
