### ISSUE TITLE
OpenWapp doesn't work

### ISSUE THREAD

**Issue by jssCAT** [mozillahispano/openwapp#206]
Hello,

From the last 2-3 days, I’m having problems with OpenWapp. I think that the last update of Whatsapp is causing problems to OpenWapp. It asks me for a PIN to sign-up. Somebody has the same problem? My smartphone is an Alcatel One Touch Fire E and the version of Firefox OS is 2.0. 

Thanks.

**Comment by Loirooriol** [comment]
Same problem on Firefox 2.2 Simulator

**Comment by Timmaks** [comment]
Dupe #204
