### ISSUE TITLE
Unable to instal OpenWapp in Alcatel Fire C Onetouch FireC 4020D mobile

### ISSUE THREAD

**Issue by kotimohan** [mozillahispano/openwapp#207]
#Hi,

I was a happy user of OpenWapp. Suddenly it stopped, tried almost every thing but won't open then I uninstalled it.

I'm trying to register, I type my phone number. And during the phone validation process, it's stopped, and I have a pop up which says "Old version, please contact OpenWapp devs".

I don't know how to find the number of version I used. I'm on the Alcatel Fire C Onetouch FireC 4020D Mobile Phone, and with Firefox OS 1.3. What I have to do ?

Thank you,

Regards,
Koti.

**Comment by Timmaks** [comment]
Dupe #204

**Comment by boi2melo** [comment]
I'm using Alcatel Firefox OS.I have been Trying to register openWapp and evertime during the phone validation a receive a message saying old version please contact openWapp devs. I need help to register and activate openWapp

**Comment by Timmaks** [comment]
We need to update the app for this. We are working on it
