### ISSUE TITLE
Old version: Contact the OpenWapp developers

### ISSUE THREAD

**Issue by djoerd** [mozillahispano/openwapp#208]
I am running version 1.9.5 from 23 January from Firefox Martketplace. I get the  error "Old version: Contact the OpenWapp developers", see: https://twitter.com/djoerd/status/713048606270472193 (in Dutch)

**Comment by Timmaks** [comment]
Dupe #204 

Er wordt aan gewerkt en hopelijk is er snel weer een nieuwe versie in de marketplace

**Comment by djoerd** [comment]
Woeps, ik dacht dat #204 iets ouds was: Fijn, bedankt!

**Comment by ngoymwembo** [comment]
My code  for my number I forgot how can get it

**Comment by ngoymwembo** [comment]
Plz help me guys

**Comment by Timmaks** [comment]
after we have updated the app you will need to enter youtr mobile number again an pres request code, it will work again
