### ISSUE TITLE
Registration Error

### ISSUE THREAD

**Issue by Tschegewara** [mozillahispano/openwapp#209]
I'm using a Flame-Smartphone with Firefox-OS 2.6 on it. When starting the registration process, I get the following Message after I fill in my phone-number:
german: Sie scheinen eine alte Version zu benutzen. Bitte aktualisieren Sie die App oder kontaktieren Sie die Openwapp Entwickler.
In English: It seems that you are using an old version. Please update the App or contact the Openwapp-Developers.

What's going wrong? I have used OpenWhapp for some time before this message.....and I tried to get the latest version out of the Firefox OS Marketplace.

Best regards,
Tsche

**Comment by Timmaks** [comment]
we are working on it, see #204 

dupe
