### ISSUE TITLE
Openwapp not appear in the marketplace.

### ISSUE THREAD

**Issue by Zeus76** [mozillahispano/openwapp#211]
Hello:

I have entered the marketplace and not the Openwapp application appears.
Does the application site is permanently deleted or an error?

Thank you!

**Comment by Loirooriol** [comment]
The link was https://marketplace.firefox.com/app/openwapp/. Now it says
> Oh, no! The requested content is not public.

**Comment by willyaranda** [comment]
I removed the app from being public as it does not work anymore.

I need to do a update saying that users should migrate to Loqui, as it works with new e2e encryption for Whatsapp.

Thanks for all guys
