### ISSUE TITLE
Conversation view spacing

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/openwapp#5]
Reduce the conversation view spacing by presenting the user photo on the left side and the date on the top right side (instead of a new line)

![ad79b14c-62b0-11e4-8b2d-5636bb07c67c](https://cloud.githubusercontent.com/assets/531906/4877373/010de5a0-62e6-11e4-9ec8-953fc0a1cbfe.png)

**Comment by fjaguero** [comment]
We should use some rules for the dates to get more white space in some cases (29/12) or a better readability (Yesterday). The full hour/date is not necessary.

This can be:
- Messages in the same day (17:32)
- Messages in the week (yesterday, 2 days ago)
- Messages in previous week and same year (Jul 25)
- Messages in other year (14/12/2014)

I can start with this if we all agree.

**Comment by nukeador** [comment]
@fjaguero sounds good, it's what other apps do. Go for it!

**Comment by fjaguero** [comment]
Awesome
