### ISSUE TITLE
Requesting the code per sms fails for certain numbers with the no_routes error

### ISSUE THREAD

**Issue by duesenfranz** [mozillahispano/openwapp#61]
Because this bug developed into being out of scope of #47, I decided to open a new issue on behalf of @Otsche / @Shadow1g. I'm running out of ideas :sunny:

Description
---------------

CoSeMe sms request fails for certain numbers with the error code ``no_routes``. The full error code is 
``{"status":"fail","reason":"no_routes","retry_after":3600}``. Only few numbers seem to be affected, switching any digits brings up a clean ``sent`` response. The error also occures using whatsAPI; but the sms is sent without errors using the official WA client (with *and* without sim card).

Reproducing
-----------------
One of the affected numbers is ``(+49) 16097996508``; the carrier for this number is congstar.
The error can be reproduced using
* curl

  The request can be stripped down to ``curl -k "https://v.whatsapp.net/v2/code?cc=49&in=16097996508&method=sms&id=s7.%C2%8D%C3%B8%C3%87xU*%2B%5D%C2%9E%C3%96%C3%8DH%C2%BA'a%05%C2%9F&token=YnIoScmd4y4qZ%2FxidbXl6J0Lfxo%3D" -H "Accept: text/json" -H "User-Agent: WhatsApp/2.11.431 Android/4.3 Device/GalaxyS3" -v`` without changing the error message.

* WhatsAPI

  Clone WhatsAPI, go to ``/examples``, edit ``registerTool.php`` and insert *any* string as identity. Request the code for the given number.

*  OpenWapp

  Try to request a code for the given number.

Strange
----------

**The request can be boiled down to only include ``cc, in, method, id`` and ``token``, where ``id`` can be changed, without changing the error message**
  * Also using the correct codes as lg and lc do not seem to affect this, I tried ``lc=DE&lg=de``
  * This could mean that the faulty parameter lies within one of these: ``cc, in and token``
    * The official client worked without knowing mcc/mnc; setting lc&lg correct doesn't do anything, method shouldn't do anything
    * Wrong token seems unlikely / would mean error message is a lie
    * ???

The old bug is here #47 with maybe more relevant information.

**Comment by GaboLuque** [comment]
Hace unos días obtuve un código de whatsapp emulando android. Al colocar el código en Openwapp obtuve este mensaje:
![2014-12-31-13-12-20](https://cloud.githubusercontent.com/assets/7518032/5593329/7ea50d70-91d7-11e4-9a05-cc310c66db42.png)

**Comment by willyaranda** [comment]
Las contraseñas son diferentes entre Android y OpenWapp. El PIN no puede funcionar.

Un saludo

**Comment by rduivenvoorde** [comment]
I have this problem also with a dutch reseller provider (HEMA) working with KPN network.
running latest version of today (2 jan 2015, where can I find a version number?)

To check if it was provider/SIM related, I inserted this same SIM in another (android) phone with official Whatsapp client, and succeeded in 'normal' registration there.
Hoping that I won a 'ok'-flag somewhere on WA servers, I went back to the FF/OpenWapp phone and tried to register there, but kept getting the 'No cell routes' error there.

The first time I got another error:
"No SIM-Card was detected for this number. Please choose a carrier below"
I did, but got the same old error.

After stopping OpenWapp and opening it again, but now upon starting OpenWapp I was immidiatly asked to choose which SIM to use (it's in SIM2 by the way).
In settings I hvae 'Outgoing calls' on SIM1, 'Outgoing msgs' on 'Always ask' and 'Data' on SIM1 (but I also tested to put that one on SIM2 )

Let me know if there is something else you want me to try/test.

**Comment by totolatotla13** [comment]
hola, buenas noches, openwapp dejo de funcionar, me pide un codigo.

solicito el codigo y no lo recibo en la pantalla me aparece un mensaje diciendo que no hay rutas
para enviar el mensaje a su operador. pruebe tarde, o cpntacte con los desarrolladores de openwapp.

soy de mexico mi numero de celular es +523317771617
mi operador de telefonia es telefonica movistar.

agradecere su ayuda.

arnoldo gonzalez

**Comment by antoniobeta** [comment]
Hola, you uso firefox 1.3 y tengo el problema de que me dice que no hay rutas para enviar el mensaje. ¿Como lo soluciono?

**Comment by VictorOsorioMedrano** [comment]
Tranquilos, es un bug que ya esta confirmada su solucion en la proxima version, esperen unos dias mas para que salga en forma de actualizacion y el problema quede solucionado ;)

**Comment by antoniobeta** [comment]
Ok, muchisimas gracias.
Pd. También me pasa con las otras apps, por si os sirve de ago.

**Comment by holztest08** [comment]
Is there a new way to request the code via curl?

**Comment by nukeador** [comment]
It seems this problem only affects some users, since we have been able to register using a Spanish SIM card.

**Comment by nukeador** [comment]
Can you please try to register disabling WiFi and ensuring you have a SIM card with data enabled?

**Comment by Insurrectionist** [comment]
I tried that nukeador and I got the same message. I'm using a Movistar ZTE Open II.

**Comment by holztest08** [comment]
I also tried it with data enabled and two different sim cards, got the same message.
Latest version of connecta2 (0.17h) works for me.

**Comment by duesenfranz** [comment]
@holztest08 Thanks! Indeed, the request that connectA2 sends seems to work:

    curl -k "https://v.whatsapp.net/v2/code?cc=49&in=16097996508&method=sms&id=s7.%C2%8D%C3%B8%C3%87xU*%2B%5D%C2%9E%C3%96%C3%8DH%C2%BA'a%05%C2%9F&token=9d1be5dd6fcf146f3469bfd1191077f4" -H "Accept: text/json" -H "User-Agent: WhatsApp/2.12.60 S40Version/14.26 Device/Nokia302" -v

(sorry @Shadow1g ;))

Note that this seems to be because of the Nokia user-agent (the server is probably nicer to old, not-so-much supported devices).

Unfortunately they obfuscate their code, so I don't really know what their full ``tokenData`` is. (Should be googable however)

**Comment by antoniobeta** [comment]
Hola, me gustaria informar de que Conecta2 ya si funciona, por si podeis mirar como han solucionado ellos el error, como aqui es todo OPEN SOURCE.

Larga vida al OPEN!

**Comment by nukeador** [comment]
@antoniobeta as far as I know connecta2 doesn't publish their source code or it's open/libre software.

**Comment by duesenfranz** [comment]
Probably related [commit at yowsup](https://github.com/tgalal/yowsup/commit/1279940031d129045a17d8ba1a5aaf8863fea065)

People [report](https://github.com/tgalal/yowsup/issues/370) that it was fixed by this commit.

**Comment by antoniobeta** [comment]
@nukeador on its makerplace page its sais  Creative Commons License: CC - BY - NC -ND
so even they havent got github i supose that if you askt they for their code they should give it to you.

**Comment by nukeador** [comment]
@antoniobeta That's not a open source license: No commercial - **No derivatives**.

I haven't use CC for code, so I don't know if they are obligated to disclose the code even you can't modify it.

**Comment by antoniobeta** [comment]
@nukeador Sorry, I havent noticed that.

**Comment by bl4z3r3d** [comment]
I confirm this bug. A phone number from Brazil. Got the same error.

**Comment by JayVii** [comment]
Loqui.IM supposedly fixed that issue in their v4 branch that will soon to be merged. However i am not able to test until they pushed it to the marketplace. Maybe their fix could also work for OW

**Comment by holztest08** [comment]
I just tested loqui v4 branch with simulator. For my phone number (germany) it doesn't work.

**Comment by willyaranda** [comment]
@holztest08 I would say that Loqui does not work on the simulator unless they implement a way to select the carrier like @duesenfranz did, so they can send a correct mcc/mnc pair.

Please test it on a real phone with a valid SIM card.

**Comment by xilux** [comment]
Same problem here with my new Alcatel oneTouch Fire E and a Congstar SIM. I already have the app running on my old OneTouch Fire. But on the new phone with the same SIM I get the message in German. Translated: 'Not able to connect to send a SMS (text-message). Please try later.'

**Comment by SunboX** [comment]
Same for me with Congstar SIM on my new (used) Nexus 4 running Firefox OS 2.2.

**Comment by willyaranda** [comment]
Locking. We know that we have problems with every carrier.

**Comment by willyaranda** [comment]
1.7.3 fixed this. Closing and unlocking.

**Comment by xilux** [comment]
tested ok
Works fine now

Thank you

**Comment by antoniobeta** [comment]
Testing on a ZTE Open C with an Spanish number, I got the code and the app works perfectly.
Thanks to the developers!

**Comment by SunboX** [comment]
Same for FxOS 3.0 on Nexus 4 with German Congstar number. Thank you all, very much!

**Comment by wolfmat** [comment]
hey guys. would be usefull if you write simple troubleshooting instructions  (for different devices/versions) in the top of this issue. i'm having this issue on a flame device, have been reading trhough comments and the issue and can't seem to find the solution.

having clear troubleshooting instructions would be helpfull.

thanks!
