### ISSUE TITLE
Unable to register with a presently whatsapp using mobile number (migration from other phone to Fire fox os

### ISSUE THREAD

**Issue by mansoorkdp** [mozillahispano/openwapp#69]
I used to have a android device samsung mobile phone and i used to have whatsapp on my mobile number and once i lost the sim and now when i try to register this mobile number is not getting registered please help

**Comment by shuvangi** [comment]
Ok i ll try my best to unblock myself thanks for helpng me out, i ll let u know whatever happens  n yes happy new year to u and ua family as well

**Comment by nukeador** [comment]
Let continue in #61
