### ISSUE TITLE
Send time instead of phonetime

### ISSUE THREAD

**Issue by Timmaks** [mozillahispano/openwapp#72]
The time in bubble uses the time of the phone, but at the moment the Flame has a bug and after a system update the time is not correctly set until you enter your PIN. Result a message received while not enter the PIN yet but connected to WIFI has a different time as the messages received after entering the PIN and the message flow is not in order.

Can the send time of the message be used so the order of messages are always in the order as send?

**Comment by duesenfranz** [comment]
Does this bug still exist? In which version of FFOS?

**Comment by Timmaks** [comment]
It was noted on ffos 2.1 but i think this is not something tied to a ffos version.

**Comment by Timmaks** [comment]
![2015-01-12-12-23-09](https://cloud.githubusercontent.com/assets/9842548/5815013/bc893378-a091-11e4-9fd7-7f054478ffbf.png)

**Comment by hectorfhurtado** [comment]
HI, I'm using FFOS v2.0  and I have the same bug

**Comment by timothymctim** [comment]
I have this issue too.  `meta.date` should be replaced by the date of the received message.  It's also a problem if OpenWapp receives a bunch of new messages when it's again on-line after being off-line for a while.

Although I'm quite sure WhatsApp includes a timestamp of the received message, I didn't find any code related to this in Coseme (actually, I didn't even find the code that processes received messages).

**Comment by telefrancisco** [comment]
Same bug in 1.3

The issue is serious not for the time itself, but because when receiving a bunch (~>10) of messages they're shown in no particular order, so the conversation is impossible to follow.

**Comment by bobcanthelpyou** [comment]
I also don't access Openwapp daily. Messages are show as received when i access Openwapp. That is often confusing when contacts have written something about where they are and about meetings, cause i actually don't know when the messages where written.

**Comment by naitsirch** [comment]
I have created a PR, which addresses this feature ;-)

**Comment by telefrancisco** [comment]
Very nice. @willyaranda / @Timmaks can you please merge it and release a new version so we can test it? Thanks.

**Comment by willyaranda** [comment]
@telefrancisco will release a new version with some changes in the next few days

**Comment by telefrancisco** [comment]
@willyaranda Thanks.
