### ISSUE TITLE
Use l10n.js instead of a custom l10n code.

### ISSUE THREAD

**Issue by willyaranda** [mozillahispano/openwapp#77]
And move translations to transifex, or other site that can keep tracking of l10n changes.

This is a easy change, but big. Who wants to own it?

**Comment by Timmaks** [comment]
Taking together with @rduivenvoorde

**Comment by Timmaks** [comment]
I have trouble with finding the way to use l10n.js together with handlebars (hbs template). have anyone a solution for this?

**Comment by duesenfranz** [comment]
@Timmaks I'm pretty shure you have to adapt [this function](https://github.com/mozillahispano/openwapp/blob/f479108c59f30ad09133206ef0c1628ced9b0109/app/scripts/templates/helpers.js#L84-L86)

As far as I understood it, all the helpers exported here can be used within the templates as ``{{$helper_name '$argument1' ['$argument2' etc.]}}``

**Comment by Timmaks** [comment]
@duesenfranz i tried already that but my knowledge is to limited :(

@willyaranda sure but because of the way the html is pre generated bij handbar.js i don't get that to work yet so i was hoping someone had experience with this before i spend days to solve it.

I found a presentation of Fabien Cazenave on FOSDEM 2013 where he mention handlebar.js as next thing to integrate (http://kazhack.org/public/slides/fosdem13/?full#next) but nothing that it happened.

**Comment by Timmaks** [comment]
I reached out to one of the l10n drivers and contributer to the l10n.js of mozilla and he told me that the version where mdn point to is not the version that is used by FFOS anymore. If i use the version of FFOS he is happy to help me :-)

I am not sure anymore witch version i used in all the different tryings so i am going to start over  next weekend and hope i can figure it out with his help

**Comment by Timmaks** [comment]
Yes with a good hint of Gandalf i found the (my) problem and got it working, pull request will follow soon after @rduivenvoorde and i have converted all the files

**Comment by willyaranda** [comment]
That's great! Eager to see the PR :)

(self-asigned incorrectly :( )

**Comment by Timmaks** [comment]
----Progress report----

Making good process with the port (after a slow, trouble start).
- i adopted the template helper , https://github.com/Timmaks/openwapp/blob/master/app/scripts/templates/helpers.js so it uses l10n.js in all the templates but i also rewriting most of the templates to use l10n.js directly (i couldn't find a way to change the placeholders en input values in i.e. https://github.com/Timmaks/openwapp/blob/master/app/scripts/templates/login.hbs but for that we can keep the helper in place
- porting the js files is a work in progress

Building the app with grunt gives a lot of warnings on the l10n.js file so i can only build it with grunt--force, 

please have a look on the changes so far (don't look at the main.js, i have to clean the testing there)

**Comment by willyaranda** [comment]
@Timmaks can you send a PR and discuss there? thanks

**Comment by Timmaks** [comment]
i wanted to do the pr when i have done all the files.

**Comment by willyaranda** [comment]
you can do a PR now, continue working on your branch with my comments, and
when all is correct, squash the changes, and merge a shiny and brigt PR
with one commit

**Comment by Timmaks** [comment]
Right, i change my mind about rewriting the template files, it give to mutch problems and changing the helper does the job.

PR #91 is ready. now i going to setup transifex

**Comment by willyaranda** [comment]
https://www.transifex.com/projects/p/twitta/ is on transifex

**Comment by Timmaks** [comment]
@willyaranda yaeh. The only thing is that the form to add a project to https://www.transifex.com/organization/mozilla-tech-evangelism on MDN is not working so i wait for a administrator to help :-) 

I think that group is good place for Openwapp

**Comment by willyaranda** [comment]
Yeah, perfect. I'm going to move the project to that organization.

**Comment by willyaranda** [comment]
@Timmaks I just sent a request to join that organization.

**Comment by Timmaks** [comment]
@willyaranda let's see who is faster :-)

**Comment by Timmaks** [comment]
https://www.transifex.com/projects/p/openwapp/ is ready to go!
