### ISSUE TITLE
unable to register

### ISSUE THREAD

**Issue by piyushsingh600** [mozillahispano/openwapp#85]
Updating new open wapp. I am unable to register shows the error after entering mobile number. Please resolve issues.following error- 
no cell routes for sending sms caused by your operator please try again later or contact with open wapp devloer.
Device name-alcatel onetouch firec
operator-vodafone
country-india
connection using sim

**Comment by scrooge74** [comment]
Same here, Panama operator Cable & Wireless

**Comment by nukeador** [comment]
#69
