### ISSUE TITLE
Prefix is not correct for Russia

### ISSUE THREAD

**Issue by willyaranda** [mozillahispano/openwapp#89]
>
And one more bug, when i choose country, i select Russian Federation and there posted code +79, but Russian Federation country code is +7, but not +79.
See here: http://en.wikipedia.org/wiki/Telephone_numbers_in_Russia

On #88 by @inpu

**Comment by duesenfranz** [comment]
The error is in [countries.json](https://github.com/mozillahispano/openwapp/blob/f479108c59f30ad09133206ef0c1628ced9b0109/app/scripts/countries.json#L746), as expected. It also exists upstream, in [countries.csv](https://github.com/musalbas/mcc-mnc-table/blob/76f514a118e313cfa4748463add04101bda6bba6/mcc-mnc-table.csv#L1076), who have it from [mcc-mnc.com](http://mcc-mnc.com/). I called them and they'll fix it. (a matter of days probably)

@willyaranda  should I push a manual fix meanwhile?

**Comment by willyaranda** [comment]
@duesenfranz yes, please.

**Comment by duesenfranz** [comment]
@inpu thanks for the report!
