### ISSUE TITLE
missing notification icon

### ISSUE THREAD

**Issue by SunboX** [mozillahispano/openwapp#90]
![2015-01-28-20-56-11](https://cloud.githubusercontent.com/assets/83344/5946088/7b3d47f8-a733-11e4-95fe-e5907885384a.png)

**Comment by SunboX** [comment]
![2015-01-28-21-34-19](https://cloud.githubusercontent.com/assets/83344/5946521/af242b24-a736-11e4-9a8b-8ccafecb6e44.png)

**Comment by willyaranda** [comment]
duplicate from #11
