### ISSUE TITLE
Unable to complete update: return to old state possible?

### ISSUE THREAD

**Issue by dsalewski** [mozillahispano/openwapp#92]
Hello NG, 

since two days I've got a download/update problem with whatsapp on my Flame (which is not unimportant to me, since I use the Flame as my only device...). 

Symptoms: 
1) Probably afternoon of 05.02.2015: First update of openwapp indicated on my phone - everything went very well. Openwapp still fully functional. 
2) Probably late evening of 05.02.2015 or morning of 06.02.2015: again an availiable update indicated on my phone. Execution of download FAILED. 
3) Since then: 
a) the icon of openwhapp is a white round arrow on pale gray ground, and if I hit the button it says: "download openwapp", which fails every time.
b) Receiving messages seems still to work - I get the "incoming message" beep and the first two lines of the message on my lock screen. But I can't access the app itself.

Questions:
1) Is it possible to just alter some config file to stop openwapp from thinking that it has to update itself before opening the start screen? 
2) Does anybody know another fix for this? 
3) If not: is it possible to at least save my configuration, my Whatsapp-Password and ideally the conversations before I have to reinstall openwapp. How would I do that? 

Greetings 

Dirk

**Comment by willyaranda** [comment]
Hi @dsalewski 

This is a problem with Firefox OS, not with Openwapp. What is your Firefox OS version?

Openwapp conversations save the data in a IndexedDB database, which is stored where the OS decides, but should be somewhere :)

For the "password", you can do a `localStorage.get('openwapp_seed');` and paste into the new installation.

**Comment by willyaranda** [comment]
(closing, since this is not an issue of openwapp, but we can still discuss here)
