### ISSUE TITLE
Not validating a valid phone number

### ISSUE THREAD

**Issue by birdsarah** [mozillahispano/openwapp#94]
Hi,

Very excited to see openwapp.

Am running openwapp (v1.7.4) on my ffos phone (v1.4), installed via the marketplace.

When trying to Sign-up I am asked for my phone number. It is a US number (+1) I have tried both `6173334444` and `617-333-4444` versions of entering it.

In both cases I get the message: 

````
Oops, error.Message={
    "status": "fail",
    "reason": "bad_param",
    "param": "number"
}
````

**Comment by willyaranda** [comment]
@birdsarah Are you using your US simcard, right? Is it the SIM for the number you have introduced?

**Comment by birdsarah** [comment]
Hi! Thanks for the quick reply. 

I was trying to use my google voice number (which I often use to forward SMS). I rarely use my actual mobile number so that I have a buffer for spam. 

It's working when I use my actual number.

Sorry for bothering you, and thanks so much for the quick reply.

Maybe I'll do a pull request for a more informative error message.

Thanks again!

**Comment by willyaranda** [comment]
Hey,

that message comes directly from WA, we don't parse it, yet. a `bad_param`  with a `number` means that your number is incorrect for them, but we allow it to pass the verification.

So if you have any idea for a message and a PR, that will be awesome!
