### ISSUE TITLE
Must register again after telephone restart

### ISSUE THREAD

**Issue by VMbuseck** [mozillahispano/openwapp#97]
Openwapp: 1.7.4-0-ge417a1a
Firefox OS: 1.3.0.0.prerelease
Device: Alcatel One touch fire

After a restart of the device openwapp requests for a confirmation code. The correct phone number is displayed, but the code received the last time will not been accepted. I had to register again and receive a new code via sms.

**Comment by telefrancisco** [comment]
Happened to me too 2 days ago, but only once so far. I tried Re-registering again and the issue has not appear anymore since.

**Comment by willyaranda** [comment]
If you have to register again, it means that WA does not recognize your current user/password. If it is working, I'm closing this :)

**Comment by VMbuseck** [comment]
It happened min. 10 times within the last 3 weeks. Now I cant register anymore (see attachment).

![2015-03-15-14-00-48](https://cloud.githubusercontent.com/assets/6317886/6656112/23711370-cb1d-11e4-98b7-dcdd16c5fce8.png)
![2015-03-15-14-01-03](https://cloud.githubusercontent.com/assets/6317886/6656113/2372b0e0-cb1d-11e4-8369-7d942c81323a.png)

**Comment by willyaranda** [comment]
This means that WA has blocked you. We can't do anything. You must contact them and try to get unblocked.
