### ISSUE TITLE
Issues when reconnecting and receiving messages .

### ISSUE THREAD

**Issue by telefrancisco** [mozillahispano/openwapp#98]
When do you reconnect data (or wifi, or restart your phone) openwapp starts to receive (and show) messages people wrote to you when you were offline.

However, when the number of messages sent in the meanwhile is somewhat big (~>10 messages) these are shown in the wrong order. So I think this a serious issue that prevents you from following the conversation.

In addition, the date/hour shown is the date of your reconnection (this is, when openwapp reconnects) instead of the "real" date (when the person sent the message).

**Comment by Timmaks** [comment]
This is issue #72

**Comment by telefrancisco** [comment]
Sorry, didn't find it. I'll close as dupe.

Thanks.
